
const ServerConstants = {
    VehicleNames : [
        "Landstalker","Bravura","Buffalo","Linerunner","Perrenial","Sentinel","Dumper","Firetruck","Trashmaster","Stretch","Manana","Infernus","Voodoo","Pony","Mule","Cheetah","Ambulance","Leviathan","Moonbeam","Esperanto","Taxi","Washington","Bobcat","Mr Whoopee","BF Injection","Hunter","Premier","Enforcer","Securicar","Banshee","Predator","Bus","Rhino","Barracks","Hotknife","Trailer 1","Previon","Coach","Cabbie","Stallion","Rumpo","RC Bandit","Romero","Packer","Monster","Admiral","Squalo","Seasparrow","Pizzaboy","Tram","Trailer 2","Turismo","Speeder","Reefer","Tropic","Flatbed","Yankee","Caddy","Solair","Berkley's RC Van","Skimmer","PCJ-600","Faggio","Freeway","RC Baron","RC Raider","Glendale","Oceanic","Sanchez","Sparrow","Patriot","Quad","Coastguard","Dinghy","Hermes","Sabre","Rustler","ZR-350","Walton","Regina","Comet","BMX","Burrito","Camper","Marquis","Baggage","Dozer","Maverick","News Chopper","Rancher","FBI Rancher","Virgo","Greenwood","Jetmax","Hotring","Sandking","Blista Compact","Police Maverick","Boxville","Benson","Mesa","RC Goblin","Hotring Racer A","Hotring Racer B","Bloodring Banger","Rancher","Super GT","Elegant","Journey","Bike","Mountain Bike","Beagle","Cropdust","Stunt","Tanker","Roadtrain","Nebula","Majestic","Buccaneer","Shamal","Hydra","FCR-900","NRG-500","HPV1000","Cement Truck","Tow Truck","Fortune","Cadrona","FBI Truck","Willard","Forklift","Tractor","Combine","Feltzer","Remington","Slamvan","Blade","Freight","Streak","Vortex","Vincent","Bullet","Clover","Sadler","Firetruck LA","Hustler","Intruder","Primo","Cargobob","Tampa","Sunrise","Merit","Utility","Nevada","Yosemite","Windsor","Monster A","Monster B","Uranus","Jester","Sultan","Stratum","Elegy","Raindance","RC Tiger","Flash","Tahoma","Savanna","Bandito","Freight Flat","Streak Carriage","Kart","Mower","Duneride","Sweeper","Broadway","Tornado","AT-400","DFT-30","Huntley","Stafford","BF-400","Newsvan","Tug","Trailer 3","Emperor","Wayfarer","Euros","Hotdog","Club","Freight Carriage","Trailer 3","Andromada","Dodo","RC Cam","Launch","Police Car (LSPD)","Police Car (SFPD)","Police Car (LVPD)","Police Ranger","Picador","S.W.A.T. Van","Alpha","Phoenix","Glendale","Sadler","Luggage Trailer A","Luggage Trailer B","Stair Trailer","Boxville","Farm Plow","Utility Trailer"
    ],
    VehicleModelNames : [
        "landstal","bravura","buffalo","linerun","peren","sentinel","dumper","firetruk","trash","stretch","manana","infernus","voodoo","pony","mule","cheetah","ambulan","leviathn","moonbeam","esperant","taxi","washing","bobcat","mrwhoop","bfinject","hunter","premier","enforcer","securica","banshee","predator","bus","rhino","barracks","hotknife","artict1","previon","coach","cabbie","stallion","rumpo","rcbandit","romero","packer","monster","admiral","squalo","seaspar","pizzaboy","tram","artict2","turismo","speeder","reefer","tropic","flatbed","yankee","caddy","solair","topfun","skimmer","pcj600","faggio","freeway","rcbaron","rcraider","glendale","oceanic","sanchez","sparrow","patriot","quad","coastg","dinghy","hermes","sabre","rustler","zr350","walton","regina","comet","bmx","burrito","camper","marquis","baggage","dozer","maverick","vcnmav","rancher","fbiranch","virgo","greenwoo","jetmax","hotring","sandking","blistac","polmav","boxville","benson","mesa","rcgoblin","hotrina","hotrinb","bloodra","bloodrb","rnchlure","supergt","elegant","journey","bike","mtbike","beagle","cropdust","stunt","petro","rdtrain","nebula","majestic","buccanee","shamal","hydra","fcr900","nrg500","copbike","cement","towtruck","fortune","cadrona","fbitruck","willard","forklift","tractor","combine","feltzer","remingtn","slamvan","blade","freight","streak","vortex","vincent","bullet","clover","sadler","firela","hustler","intruder","primo","cargobob","tampa","sunrise","merit","utility","nevada","yosemite","windsor","monstera","monsterb","uranus","jester","sultan","stratum","elegy","raindanc","rctiger","flash","tahoma","savanna","bandito","freiflat","streakc","kart","mower","duneride","sweeper","broadway","tornado","at400","dft30","huntley","stafford","bf400","newsvan","tug","petrotr","emperor","wayfarer","euros","hotdog","club","freibox","artict3","androm","dodo","rccam","launch","copcarla","copcarsf","copcarvg","copcarru","picador","swatvan","alpha","phoenix","glenshit","sadlshit","bagboxa","bagboxb","tugstair","boxburg","farmtr1","utiltr1"
    ]    
}
exports.ServerConstants = ServerConstants;